# Generated by Django 5.0.1 on 2024-01-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
